### ISSUE TITLE
When creating a contest in a negative timezone the contest dates are a day early

### ISSUE THREAD

**Issue by sheodox** [tadoku/tadoku#325]
Creating a contest in my local timezone of UTC-6 will create a contest starting and ending on the previous day to what it is in UTC. If I want to create a contest running through the month of January I need to create a contest with a start date of 2022-01-02 and an end date of 2022-02-02. This ends up creating a contest going from 2022-01-01 to 2022-02-01 like I wanted.

When I create a contest starting 2022-02-01 it will post a date string to the server like `2022-01-31T18:00:00-06:00`, and it seems to be ignoring the time zone part of that and actually creating the contest starting on `2022-01-31`.

When subsequently editing a contest this doesn't seem to stay the case, it's treated as a date in UTC time. The timestamps in use don't include my timezone.

Creating a contest for the month of January 2022
![image](https://user-images.githubusercontent.com/3468630/143154732-b775ac56-e216-496d-8ad0-0f65fbfa10a5.png)

What's posted
![image](https://user-images.githubusercontent.com/3468630/143154772-b42e12fc-21cc-4c6b-82d7-e4c184da337e.png)

How it shows up in the manage contest list
![image](https://user-images.githubusercontent.com/3468630/143154815-5b2441d7-1b9f-47aa-8df2-1add379a35f3.png)

**Comment by antonve** [comment]
Fixed in https://github.com/tadoku/tadoku/commit/e8309820ef2ba6c092a6c2cf5839b567c5bf3e38
