### ISSUE TITLE
immersion: split chinese into Mandarin/Cantonese

### ISSUE THREAD

**Issue by antonve** [tadoku/tadoku#518]

**Comment by Spooghetti420** [comment]
According to Wiktionary, the Chinese language family also includes Gan, Hakka, Huizhou, Jin, Min Bei, Min Dong, Min Nan, Min Zhong, Puxian, Hainanese, Shaojiang, Wu, and Xiang. What is the threshold for allowing a language onto Tadoku?

**Comment by antonve** [comment]
@Spooghetti420 it can be requested to be added; I'm adding them on an as-needed basis. 

As there are many dialects of Chinese I'm thinking of keeping one Language to cover all the Chinese dialects, but also have a couple of the more studied ones so they can be logged more precisely. Reason for doing so is that it's not uncommon for Chinese learners to learn multiple dialects.
